### ISSUE TITLE
No error just a question

### ISSUE THREAD

**Issue by iGetUploaded** [Az-r08/AzR-nuker#1]
How did you manage to decrypt WeLuvJah Image grabber? Was about to run it when I saw your Issue posted with it

https://github.com/WeLuvJah/Image-Grabber-v2.1

**Comment by Az-r08** [comment]
it's not even "encrypted", it's just obfuscated, you only need some basic knowledge to deobfuscate codes, also if you run it, don't panic, some nice dude alr disable the logger's webhook

**Comment by Az-r08** [comment]
also, there's no image logger or anything it's just a pure scam

**Comment by iGetUploaded** [comment]
Just started to learn how to deobfuscate codes using uncompyle6 and what not... By any chance do you know of any Image logger or they all just a scam

**Comment by Az-r08** [comment]
i doubt there is one, if it does exists, it should be patched by now, image loggers are a blatant scam at this point

**Comment by iGetUploaded** [comment]
Damn well okay appreciate the help/info man 💯
